// components/ISMRMPanel.tsx
import React, { useState, useCallback } from 'react';
import { AbstractData, GenerationMode, ImageState, AnalysisResult, AbstractTypeSuggestion, AbstractType, Category } from '../types';
import * as llm from '../lib/llm'; // Use the new dispatcher
import { SvgIcon } from './SvgIcon';
import Modal from './Modal';
import OutputDisplay from './OutputDisplay';

const ISMRMPanel: React.FC = () => {
  // Global State
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [loadingMessage, setLoadingMessage] = useState<string>('Generating...');
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'abstract' | 'figure'>('abstract');

  // Abstract State
  const [abstractMode, setAbstractMode] = useState<GenerationMode>('standard');
  const [inputText, setInputText] = useState<string>('');
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [selectedCategories, setSelectedCategories] = useState<Category[]>([]);
  const [selectedKeywords, setSelectedKeywords] = useState<string[]>([]);
  const [typeSuggestions, setTypeSuggestions] = useState<AbstractTypeSuggestion[]>([]);
  const [selectedAbstractType, setSelectedAbstractType] = useState<AbstractType | null>(null);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalStep, setModalStep] = useState<'analysis' | 'type'>('analysis');
  const [generatedAbstract, setGeneratedAbstract] = useState<AbstractData | null>(null);

  // Image State
  const [imageMode, setImageMode] = useState<GenerationMode>('standard');
  const [imageState, setImageState] = useState<ImageState>({ file: null, specs: '', base64: null });
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);

  const resetWorkflow = () => {
    setAnalysisResult(null);
    setSelectedCategories([]);
    setSelectedKeywords([]);
    setTypeSuggestions([]);
    setSelectedAbstractType(null);
    setGeneratedAbstract(null);
  }

  const handleTextChange = (text: string) => {
    setInputText(text);
    if(analysisResult) {
      resetWorkflow();
    }
  }

    const fileToBase64 = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => {
                const result = reader.result as string;
                resolve(result.split(',')[1]); // remove the data:mime/type;base64, part
            };
            reader.onerror = error => reject(error);
        });
    };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setError(null);
      
      // Clear the file input immediately to allow re-uploading the same file
      e.target.value = '';

      if (file.type !== 'text/plain') {
        setError("Only .txt files can be uploaded directly. For other formats (.pdf, .docx), please copy and paste the text manually.");
        return;
      }

      setIsLoading(true);
      setLoadingMessage(`Reading ${file.name}...`);
      try {
        const text = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = (event) => resolve(event.target?.result as string);
          reader.onerror = (err) => reject(err);
          reader.readAsText(file);
        });
        setInputText(text);
        if (analysisResult) resetWorkflow();
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to read file.');
      } finally {
        setIsLoading(false);
      }
    }
  };

  const handleImageFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      try {
        const base64 = await fileToBase64(file);
        setImageState({ ...imageState, file, base64 });
      } catch (error) {
        console.error("Error converting file to base64:", error);
        setError("Failed to read image file.");
      }
    }
  };

  const handleAnalyze = async () => {
    if (!inputText.trim()) {
        setError('Please provide input text to analyze.');
        return;
    }
    setIsLoading(true);
    setLoadingMessage('Analyzing content...');
    setError(null);
    resetWorkflow();
    try {
      const result = await llm.analyzeContent(inputText);
      setAnalysisResult(result);
      setSelectedKeywords(result.keywords);
      setModalStep('analysis');
      setIsModalOpen(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An unknown error occurred during analysis.');
    } finally {
      setIsLoading(false);
    }
  };
  
  const handleAnalysisConfirmation = async (cats: Category[], keys: string[]) => {
      setSelectedCategories(cats);
      setSelectedKeywords(keys);
      setIsLoading(true);
      setLoadingMessage('Suggesting abstract types...');
      try {
        const suggestions = await llm.suggestAbstractType(inputText, cats, keys);
        setTypeSuggestions(suggestions);
        setModalStep('type');
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Failed to get abstract type suggestions.');
        setIsModalOpen(false);
      } finally {
        setIsLoading(false);
      }
  };

  const handleTypeSelection = (type: AbstractType) => {
      setSelectedAbstractType(type);
      setIsModalOpen(false);
  }

  const handleGenerateAbstract = async () => {
    if (!inputText || !selectedAbstractType || selectedCategories.length === 0 || selectedKeywords.length === 0) {
      return setError('Please complete the analysis and selection steps before generating.');
    }
    setIsLoading(true);
    setLoadingMessage('Generating final abstract...');
    setError(null);
    setGeneratedAbstract(null);
    try {
      const result = await llm.generateFinalAbstract(inputText, selectedAbstractType, selectedCategories, selectedKeywords);
      setGeneratedAbstract(result);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An unknown error during abstract generation.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateCreative = async () => {
    if (!inputText.trim()) return setError('Please provide a core idea to expand.');
    setIsLoading(true);
    setLoadingMessage('Creatively generating abstract...');
    setError(null);
    resetWorkflow();
    try {
        const result = await llm.generateCreativeAbstract(inputText);
        setGeneratedAbstract(result);
        setSelectedKeywords(result.keywords);
    } catch (e) {
        setError(e instanceof Error ? e.message : 'An unknown error during creative generation.');
    } finally {
        setIsLoading(false);
    }
  };
  
  const handleGenerateImage = async () => {
      let context = '';
      if (imageMode === 'creative') {
          if (!generatedAbstract) {
              return setError('Please generate an abstract first to provide context for creative image generation.');
          }
          context = `Impact: ${generatedAbstract.impact}\nSynopsis: ${generatedAbstract.synopsis}`;
      } else if (!imageState.file) {
          return setError('Please upload an image for standard mode editing.');
      }

      setIsLoading(true);
      setLoadingMessage('Generating figure...');
      setError(null);
      setGeneratedImage(null);
      try {
          const result = await llm.generateImage(imageState, context);
          setGeneratedImage(`data:image/png;base64,${result}`);
      } catch (e) {
          setError(e instanceof Error ? e.message : 'An unknown error during image generation.');
      } finally {
          setIsLoading(false);
      }
  };

  return (
    <>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="flex flex-col gap-6 p-4">
          <div className="flex border-b border-base-300">
            <TabButton id="abstract" activeTab={activeTab} setActiveTab={setActiveTab} label="Abstract Generation" icon="text" />
            <TabButton id="figure" activeTab={activeTab} setActiveTab={setActiveTab} label="Figure Generation" icon="image" />
          </div>

          {activeTab === 'abstract' && (
            <div className="space-y-4 animate-fade-in">
              <ModeSelector mode={abstractMode} setMode={setAbstractMode} />
              {abstractMode === 'standard' ? (
                <div className="bg-base-100 p-4 rounded-lg">
                  <label htmlFor="file-upload" className="block text-sm font-medium text-text-secondary mb-2">
                    Upload .txt File or Paste Text
                  </label>
                  <input id="file-upload" type="file" accept=".txt,text/plain" onChange={handleFileChange} className="block w-full text-sm text-text-secondary file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-brand-primary/20 file:text-brand-primary hover:file:bg-brand-primary/30"/>
                  <div className="relative mt-2">
                    <textarea value={inputText} onChange={(e) => handleTextChange(e.target.value)} placeholder="Paste the full text of your paper here..." className="w-full h-60 p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition" />
                  </div>
                </div>
              ) : (
                <div className="bg-base-100 p-4 rounded-lg">
                  <label htmlFor="creative-prompt" className="block text-sm font-medium text-text-secondary mb-2">
                    Creative Expansion: One-Sentence Idea
                  </label>
                  <input id="creative-prompt" type="text" value={inputText} onChange={(e) => handleTextChange(e.target.value)} placeholder="e.g., Using AI to predict patient outcomes from MRI scans." className="w-full p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition" />
                </div>
              )}
              <div className="flex flex-col sm:flex-row gap-4">
                {abstractMode === 'standard' ? (
                  <>
                    <button onClick={handleAnalyze} disabled={isLoading || !inputText.trim()} className="flex-1 flex items-center justify-center gap-2 bg-base-300 hover:bg-opacity-80 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"><SvgIcon type="sparkles" className="h-5 w-5" />1. Analyze</button>
                    <button onClick={handleGenerateAbstract} disabled={isLoading || !selectedAbstractType} className="flex-1 flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"><SvgIcon type="document" className="h-5 w-5" />2. Generate</button>
                  </>
                ) : (
                  <button onClick={handleGenerateCreative} disabled={isLoading || !inputText.trim()} className="w-full flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"><SvgIcon type="sparkles" className="h-5 w-5" />Generate Creatively</button>
                )}
              </div>
            </div>
          )}

          {activeTab === 'figure' && (
            <div className="space-y-4 animate-fade-in">
                <ImageModeSelector mode={imageMode} setMode={setImageMode} creativeDisabled={!generatedAbstract} creativeTooltip="Generate an abstract first to enable this mode." />
                 {imageMode === 'standard' ? (
                    <div className="bg-base-100 p-4 rounded-lg">
                        <label htmlFor="image-upload" className="block text-sm font-medium text-text-secondary mb-2">Upload Image</label>
                        <input id="image-upload" type="file" accept="image/*" onChange={handleImageFileChange} className="block w-full text-sm text-text-secondary file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-brand-primary/20 file:text-brand-primary hover:file:bg-brand-primary/30"/>
                        {imageState.base64 && <img src={`data:image/png;base64,${imageState.base64}`} alt="Preview" className="mt-4 rounded-lg max-h-40 object-contain mx-auto"/>}
                    </div>
                ) : (
                    <div className="p-4 bg-base-100/50 rounded-lg text-center">
                        <SvgIcon type="info" className="mx-auto h-8 w-8 text-brand-primary mb-2"/>
                        <p className="text-text-secondary font-medium">Creative mode will generate a figure based on the content of your generated abstract.</p>
                    </div>
                )}
                <div className="bg-base-100 p-4 rounded-lg">
                    <label htmlFor="image-specs" className="block text-sm font-medium text-text-secondary mb-2">Image Specifications & Guidelines</label>
                    <textarea id="image-specs" value={imageState.specs} onChange={(e) => setImageState({...imageState, specs: e.target.value})} placeholder="e.g., 'Make this a grayscale T1-weighted MRI scan', 'Add arrows pointing to the hippocampus', 'Format as a 3x3 grid'." className="w-full h-32 p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition"/>
                </div>
                <button onClick={handleGenerateImage} disabled={isLoading} className="w-full flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"><SvgIcon type="image" className="h-5 w-5" />Generate Figure</button>
            </div>
          )}
        </div>
        <OutputDisplay abstract={generatedAbstract} image={generatedImage} isLoading={isLoading} error={error} loadingMessage={loadingMessage} />
      </div>
      
      {isModalOpen && analysisResult && (
        <Modal onClose={() => setIsModalOpen(false)}>
            {modalStep === 'analysis' ? (<AnalysisStep result={analysisResult} onConfirm={handleAnalysisConfirmation} />) : (<TypeSuggestionStep suggestions={typeSuggestions} onSelect={handleTypeSelection} />)}
        </Modal>
      )}
    </>
  );
};

// --- Local Components for ISMRMPanel ---

const TabButton: React.FC<{id: 'abstract' | 'figure', activeTab: string, setActiveTab: (tab: any) => void, label: string, icon: 'text' | 'image'}> = ({ id, activeTab, setActiveTab, label, icon}) => (
  <button onClick={() => setActiveTab(id)} className={`flex items-center gap-2 text-sm font-medium py-2 px-4 rounded-t-lg transition-colors duration-200 focus:outline-none ${activeTab === id ? 'border-b-2 border-brand-primary text-brand-primary' : 'text-text-secondary hover:bg-base-300/50'}`}>
    <SvgIcon type={icon} className="h-5 w-5" />{label}
  </button>
);

const ModeSelector: React.FC<{mode: GenerationMode, setMode: (mode: GenerationMode) => void}> = ({ mode, setMode }) => (
    <div className="flex bg-base-100 rounded-lg p-1">
        <ModeButton label="Standard Analysis" icon="document" active={mode === 'standard'} onClick={() => setMode('standard')} />
        <ModeButton label="Creative Expansion" icon="sparkles" active={mode === 'creative'} onClick={() => setMode('creative')} />
    </div>
);

const ImageModeSelector: React.FC<{mode: GenerationMode, setMode: (mode: GenerationMode) => void, creativeDisabled: boolean, creativeTooltip?: string}> = ({ mode, setMode, creativeDisabled, creativeTooltip}) => (
    <div className="flex bg-base-100 rounded-lg p-1">
        <ModeButton label="Standard Edit" icon="document" active={mode === 'standard'} onClick={() => setMode('standard')} />
        <ModeButton label="Creative Generation" icon="sparkles" active={mode === 'creative'} onClick={() => setMode('creative')} disabled={creativeDisabled} tooltip={creativeTooltip} />
    </div>
);

const ModeButton: React.FC<{label: string, icon: 'document' | 'sparkles', active: boolean, onClick: () => void, disabled?: boolean, tooltip?: string}> = ({label, icon, active, onClick, disabled=false, tooltip}) => (
    <div className="relative w-1/2 group">
        <button onClick={onClick} disabled={disabled} className={`w-full flex items-center justify-center gap-2 py-2 px-3 rounded-md text-sm font-semibold transition-all duration-300 ${active ? 'bg-brand-primary text-white shadow-md' : 'text-text-secondary hover:bg-base-200/50'} ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}>
            <SvgIcon type={icon} className="h-5 w-5" />{label}
        </button>
        {disabled && tooltip && <span className="absolute bottom-full z-10 mb-2 w-max bg-base-300 text-white text-xs rounded py-1 px-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none">{tooltip}</span>}
    </div>
);

const AnalysisStep: React.FC<{result: AnalysisResult, onConfirm: (cats: Category[], keys: string[]) => void}> = ({result, onConfirm}) => {
    const [selectedCats, setSelectedCats] = useState<Category[]>(result.categories.filter(c => c.probability > 0.25));
    const [selectedKeys, setSelectedKeys] = useState<string[]>(result.keywords);
    const toggleCategory = (cat: Category) => setSelectedCats(prev => prev.some(c => c.name === cat.name) ? prev.filter(c => c.name !== cat.name) : [...prev, cat]);
    const toggleKeyword = (key: string) => setSelectedKeys(prev => prev.includes(key) ? prev.filter(k => k !== key) : [...prev, key]);
    const catColorMap = { main: 'bg-category-main/20 text-category-main', sub: 'bg-category-sub/20 text-category-sub', secondary: 'bg-category-secondary/20 text-category-secondary' };
    const catBorderColorMap = { main: 'border-category-main', sub: 'border-category-sub', secondary: 'border-category-secondary' };
    return (
        <div className="space-y-4"><h2 className="text-xl font-bold text-text-primary">Analysis Complete</h2><p className="text-text-secondary">Please review and confirm the suggested categories and keywords for your abstract.</p><div><h3 className="font-semibold mb-2">Suggested Categories</h3><div className="flex flex-wrap gap-2">{result.categories.filter(c => c.probability > 0.25).map(cat => (<button key={cat.name} onClick={() => toggleCategory(cat)} className={`px-3 py-1 text-sm font-medium rounded-full border-2 transition-all ${selectedCats.some(c => c.name === cat.name) ? ` ${catBorderColorMap[cat.type]} ${catColorMap[cat.type]} ` : 'border-base-300 bg-base-100 hover:border-brand-primary'}`}>{cat.name} <span className="text-xs opacity-70">({cat.type})</span></button>))}</div></div><div><h3 className="font-semibold mb-2">Suggested Keywords</h3><div className="flex flex-wrap gap-2">{result.keywords.map(key => (<button key={key} onClick={() => toggleKeyword(key)} className={`px-3 py-1 text-sm rounded-full border-2 transition-all ${selectedKeys.includes(key) ? 'border-brand-primary bg-brand-primary/20 text-brand-primary' : 'border-base-300 bg-base-100 hover:border-brand-primary'}`}>{key}</button>))}</div></div><button onClick={() => onConfirm(selectedCats, selectedKeys)} className="w-full bg-brand-primary hover:bg-brand-secondary text-white font-bold py-2 px-4 rounded-lg mt-4">Confirm Selections & Proceed</button></div>
    );
}

const TypeSuggestionStep: React.FC<{suggestions: AbstractTypeSuggestion[], onSelect: (type: AbstractType) => void}> = ({suggestions, onSelect}) => (
    <div className="space-y-4"><h2 className="text-xl font-bold text-text-primary">Recommended Abstract Type</h2><p className="text-text-secondary">Based on your content, we recommend the following abstract types. Please select one to proceed.</p><div className="space-y-2">{suggestions.map(suggestion => (<button key={suggestion.type} onClick={() => onSelect(suggestion.type)} className="w-full text-left p-3 bg-base-100 hover:bg-base-300/50 border border-base-300 rounded-lg transition-all"><div className="flex justify-between items-center"><span className="font-semibold text-text-primary">{suggestion.type}</span><span className="text-xs font-mono px-2 py-1 bg-brand-primary/20 text-brand-primary rounded">{`${(suggestion.probability * 100).toFixed(0)}% match`}</span></div></button>))}</div></div>
);

export default ISMRMPanel;

// src/components/panels/ISMRMPanel.vue
<template>
  <div>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div class="flex flex-col gap-6 p-4">
        <div class="flex border-b border-base-300">
          <TabButton
            id="abstract"
            :active-tab="activeTab"
            :label="t('tabs.abstract_generation')"
            icon="text"
            @set-active="setActiveTab"
          />
          <TabButton
            id="figure"
            :active-tab="activeTab"
            :label="t('tabs.figure_generation')"
            icon="image"
            @set-active="setActiveTab"
          />
        </div>

        <div v-if="activeTab === 'abstract'" class="space-y-4 animate-fade-in">
          <ModeSelector :mode="abstractMode" @set-mode="setAbstractMode" />

          <div v-if="abstractMode === 'standard'" class="bg-base-100 p-4 rounded-lg">
            <label for="file-upload" class="block text-sm font-medium text-text-secondary mb-2">
              {{ t('forms.upload_file') }}
            </label>
            <input
              id="file-upload"
              type="file"
              accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
              @change="handleFileChange"
              class="block w-full text-sm text-text-secondary file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-brand-primary/20 file:text-brand-primary hover:file:bg-brand-primary/30"
              aria-label="Upload PDF or DOCX file"
            />
            <div class="relative mt-2">
              <textarea
                v-model="inputText"
                @input="handleTextChange"
                :placeholder="t('forms.paste_text')"
                class="w-full h-60 p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition"
                aria-label="Input text for abstract generation"
              />
            </div>
          </div>

          <div v-else class="bg-base-100 p-4 rounded-lg">
            <label for="creative-prompt" class="block text-sm font-medium text-text-secondary mb-2">
              {{ getMemeTranslation('Creative Expansion', t) || t('forms.creative_prompt') }}
            </label>
            <input
              id="creative-prompt"
              type="text"
              v-model="inputText"
              @input="handleTextChange"
              :placeholder="t('forms.creative_placeholder')"
              class="w-full p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition"
            />
          </div>

          <div class="space-y-3">
            <div class="flex flex-col sm:flex-row gap-4">
              <template v-if="abstractMode === 'standard'">
                <button
                  @click="handleAnalyze"
                  :disabled="isLoading || !inputText.trim()"
                  class="flex-1 flex items-center justify-center gap-2 bg-base-300 hover:bg-opacity-80 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed focus:outline-none focus:ring-3 focus:ring-brand-primary"
                  aria-label="Analyze content to extract categories and keywords"
                >
                  <SvgIcon type="sparkles" class="h-5 w-5" />{{ t('buttons.analyze_content') }}
                </button>
                <button
                  @click="handleGenerateAbstract"
                  :disabled="isLoading || !selectedAbstractType"
                  class="flex-1 flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed focus:outline-none focus:ring-3 focus:ring-brand-primary"
                  aria-label="Generate spec-compliant abstract"
                >
                  <SvgIcon type="document" class="h-5 w-5" />{{ t('buttons.generate_abstract') }}
                </button>
              </template>
              <button
                v-else
                @click="handleGenerateCreative"
                :disabled="isLoading || !inputText.trim()"
                class="w-full flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed focus:outline-none focus:ring-3 focus:ring-brand-primary"
                aria-label="Generate creative abstract from core idea"
              >
                <SvgIcon type="sparkles" class="h-5 w-5" />{{
                  getMemeTranslation('Generate Creatively', t) || t('buttons.generate_creatively')
                }}
              </button>
            </div>

            <!-- Save and Clear buttons -->
            <div class="flex gap-3">
              <button
                @click="handleSaveAbstract"
                :disabled="!generatedAbstract || isLoading"
                class="flex-1 flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"
                title="Save abstract to Abstract Manager"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="h-5 w-5"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"
                  />
                </svg>
                {{ t('buttons.save_abstract') }}
              </button>
              <button
                @click="handleClear"
                :disabled="isLoading"
                class="flex-1 flex items-center justify-center gap-2 bg-red-600 hover:bg-red-700 text-white font-semibold py-2 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed"
                title="Clear all data and reset"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="h-5 w-5"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
                  />
                </svg>
                {{ t('buttons.clear_all') }}
              </button>
            </div>

            <!-- Deep Update button - only show after abstract generation -->
            <button
              v-if="generatedAbstract?.abstract"
              @click="handleDeepUpdate"
              :disabled="isLoading"
              class="w-full flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-700 text-white font-semibold py-2 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed animate-fade-in"
              title="Deep dive refinement using advanced prompts"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                class="h-5 w-5"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"
                />
              </svg>
              {{ t('buttons.deep_update') }}
            </button>
          </div>
        </div>

        <div v-if="activeTab === 'figure'" class="space-y-4 animate-fade-in">
          <ImageModeSelector
            :mode="imageMode"
            :creative-disabled="!generatedAbstract"
            :creative-tooltip="t('tooltips.creative_mode_disabled')"
            @set-mode="setImageMode"
          />
          <div v-if="imageMode === 'standard'" class="bg-base-100 p-4 rounded-lg">
            <label for="image-upload" class="block text-sm font-medium text-text-secondary mb-2">
              Upload Image
            </label>
            <input
              id="image-upload"
              type="file"
              accept="image/*"
              @change="handleImageFileChange"
              class="block w-full text-sm text-text-secondary file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-brand-primary/20 file:text-brand-primary hover:file:bg-brand-primary/30"
            />
            <img
              v-if="imageState.base64"
              :src="`data:image/png;base64,${imageState.base64}`"
              alt="Preview"
              class="mt-4 rounded-lg max-h-40 object-contain mx-auto"
            />
          </div>
          <div v-else class="p-4 bg-base-100/50 rounded-lg text-center">
            <SvgIcon type="info" class="mx-auto h-8 w-8 text-brand-primary mb-2" />
            <p class="text-text-secondary font-medium">
              Creative mode will generate a figure based on the content of your generated abstract.
            </p>
          </div>
          <div class="bg-base-100 p-4 rounded-lg">
            <label for="image-specs" class="block text-sm font-medium text-text-secondary mb-2">
              {{ t('forms.image_specs') }}
            </label>
            <textarea
              id="image-specs"
              v-model="imageState.specs"
              placeholder="e.g., 'Make this a grayscale T1-weighted MRI scan', 'Add arrows pointing to the hippocampus', 'Format as a 3x3 grid'."
              class="w-full h-32 p-3 bg-base-100 border border-base-300 rounded-md focus:ring-2 focus:ring-brand-primary focus:outline-none transition"
            />
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <button
              @click="handleGenerateImage"
              :disabled="isLoading"
              class="w-full flex items-center justify-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed focus:outline-none focus:ring-3 focus:ring-brand-primary"
              aria-label="Generate figure based on specifications"
            >
              <SvgIcon type="image" class="h-5 w-5" />{{ t('buttons.generate_figure') }}
            </button>
            <button
              @click="handleGenerateNanobana"
              :disabled="isLoading"
              class="w-full flex items-center justify-center gap-2 bg-orange-600 hover:bg-orange-700 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 disabled:bg-base-300/50 disabled:cursor-not-allowed focus:outline-none focus:ring-3 focus:ring-brand-primary"
              aria-label="Nanobana enhanced figure generation"
              title="Premium Nanobana Pro 3 (coming soon)"
            >
              🔥 Nanobana🍌
            </button>
          </div>
        </div>
      </div>

      <OutputDisplay
        :abstract="generatedAbstract"
        :impact="impact"
        :synopsis="synopsis"
        :categories="selectedCategories"
        :keywords="selectedKeywords"
        :image="generatedImage"
        :is-loading="isLoading"
        :error="error"
        :loading-message="loadingMessage"
        conference="ISMRM"
        :abstract-type="selectedAbstractType || undefined"
      />
    </div>

    <Modal v-if="isModalOpen && analysisResult" @close="isModalOpen = false">
      <AnalysisStep
        v-if="modalStep === 'analysis'"
        :result="analysisResult"
        :impact="impact"
        :synopsis="synopsis"
        @confirm="handleAnalysisConfirmation"
      />
      <TypeSuggestionStep v-else :suggestions="typeSuggestions" @select="handleTypeSelection" />
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import type {
  AbstractData,
  GenerationMode,
  ImageState,
  AnalysisResult,
  AbstractTypeSuggestion,
  AbstractType,
  Category,
} from '@/types';
import * as llm from '@/lib/llm';
import SvgIcon from '@/components/ui/SvgIcon.vue';
import Modal from '@/components/ui/Modal.vue';
import OutputDisplay from '@/components/OutputDisplay.vue';
import { fileProcessingService } from '@/lib/file/FileProcessingService';
import { useSettings } from '@/composables/useSettings';
import { useAbstract } from '@/composables/useAbstract';
import { getMemeTranslation } from '@/lib/i18n';

// Import sub-components
import TabButton from './ISMRMPanelComponents/TabButton.vue';
import ModeSelector from './ISMRMPanelComponents/ModeSelector.vue';
import ImageModeSelector from './ISMRMPanelComponents/ImageModeSelector.vue';
import AnalysisStep from './ISMRMPanelComponents/AnalysisStep.vue';
import TypeSuggestionStep from './ISMRMPanelComponents/TypeSuggestionStep.vue';

const { t } = useI18n();
const { settings, databaseService } = useSettings();
const { abstractToLoad, clearLoadedAbstract } = useAbstract();

// Global State
const isLoading = ref<boolean>(false);
const loadingMessage = ref<string>(t('output.generating'));
const error = ref<string | null>(null);
const activeTab = ref<'abstract' | 'figure'>('abstract');

// Abstract State
const abstractMode = ref<GenerationMode>('standard');
const inputText = ref<string>('');
const analysisResult = ref<AnalysisResult | null>(null);
const selectedCategories = ref<Category[]>([]);
const selectedKeywords = ref<string[]>([]);
const impact = ref<string>('');
const synopsis = ref<string>('');
const typeSuggestions = ref<AbstractTypeSuggestion[]>([]);
const selectedAbstractType = ref<AbstractType | null>(null);
const isModalOpen = ref<boolean>(false);
const modalStep = ref<'analysis' | 'impactSynopsis' | 'type'>('analysis');
const generatedAbstract = ref<AbstractData | null>(null);

// Image State
const imageMode = ref<GenerationMode>('standard');
const imageState = ref<ImageState>({ file: null, specs: '', base64: null });
const generatedImage = ref<string | null>(null);

const resetWorkflow = () => {
  analysisResult.value = null;
  selectedCategories.value = [];
  selectedKeywords.value = [];
  impact.value = '';
  synopsis.value = '';
  typeSuggestions.value = [];
  selectedAbstractType.value = null;
  generatedAbstract.value = null;
};

const handleTextChange = () => {
  if (analysisResult.value) {
    resetWorkflow();
  }
};

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.split(',')[1]); // remove the data:mime/type;base64, part
    };
    reader.onerror = (err) => reject(err);
  });
};

const handleFileChange = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    const file = target.files[0];
    error.value = null;

    // Clear the file input immediately to allow re-uploading the same file
    target.value = '';

    isLoading.value = true;
    loadingMessage.value = t('loading_messages.processing_file', { filename: file.name });

    try {
      // Use FileProcessingService for PDF and DOCX
      const result = await fileProcessingService.processFile(file);

      if (result.success && result.content) {
        inputText.value = result.content;
        if (analysisResult.value) resetWorkflow();
      } else if (result.error) {
        const errorMessage = fileProcessingService.getErrorMessage(result.error);
        error.value = errorMessage + ' You can also paste text directly into the text area.';
      }
    } catch (err) {
      error.value =
        err instanceof Error
          ? err.message
          : 'Failed to process file. Please try pasting the text directly.';
    } finally {
      isLoading.value = false;
    }
  }
};

const handleImageFileChange = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  if (target.files && target.files[0]) {
    const file = target.files[0];
    try {
      const base64 = await fileToBase64(file);
      imageState.value = { ...imageState.value, file, base64 };
    } catch (err) {
      console.error('Error converting file to base64:', err);
      error.value = 'Failed to read image file.';
    }
  }
};

const handleAnalyze = async () => {
  if (!inputText.value.trim()) {
    error.value = 'Please provide input text to analyze.';
    return;
  }
  isLoading.value = true;
  error.value = null;
  resetWorkflow();

  try {
    // Step 1: Analyze content
    loadingMessage.value = t('loading_messages.analyzing_content');
    const result = await llm.analyzeContent(inputText.value);

    // Validate and sanitize the result
    const validatedResult = {
      categories: Array.isArray(result?.categories) ? result.categories : [],
      keywords: Array.isArray(result?.keywords) ? result.keywords : [],
    };

    analysisResult.value = validatedResult;
    const categories = validatedResult.categories;
    const keywords = validatedResult.keywords;
    selectedCategories.value = categories.filter((c) => c && c.probability > 0.25);
    selectedKeywords.value = keywords;

    // Step 2: Generate Impact & Synopsis
    loadingMessage.value = t('loading_messages.generating_impact_synopsis');
    const impactSynopsisResult = await llm.generateImpactSynopsis(
      inputText.value,
      categories.filter((c) => c.probability > 0.25),
      keywords
    );
    impact.value = impactSynopsisResult.impact;
    synopsis.value = impactSynopsisResult.synopsis;

    // Step 3: Suggest abstract types
    loadingMessage.value = t('loading_messages.suggesting_abstract_types');
    const suggestions = await llm.suggestAbstractType(inputText.value, categories, keywords);
    // Ensure suggestions is an array
    const validSuggestions = Array.isArray(suggestions) ? suggestions : [];
    typeSuggestions.value = validSuggestions;

    // Open modal to show results
    modalStep.value = 'analysis';
    isModalOpen.value = true;
  } catch (e) {
    console.error('Analysis error:', e);
    error.value = e instanceof Error ? e.message : 'An unknown error occurred during analysis.';
  } finally {
    isLoading.value = false;
  }
};

const handleAnalysisConfirmation = (
  cats: Category[],
  keys: string[],
  impactText: string,
  synopsisText: string
) => {
  selectedCategories.value = cats;
  selectedKeywords.value = keys;
  impact.value = impactText;
  synopsis.value = synopsisText;
  modalStep.value = 'type';
};

const handleTypeSelection = (type: AbstractType) => {
  selectedAbstractType.value = type;
  isModalOpen.value = false;
};

const handleGenerateAbstract = async () => {
  if (
    !inputText.value ||
    !selectedAbstractType.value ||
    selectedCategories.value.length === 0 ||
    selectedKeywords.value.length === 0 ||
    !impact.value ||
    !synopsis.value
  ) {
    error.value = 'Please complete the analysis and selection steps before generating.';
    return;
  }
  isLoading.value = true;
  loadingMessage.value = t('loading_messages.generating_abstract');
  error.value = null;
  generatedAbstract.value = null;
  try {
    const result = await llm.generateFinalAbstract(
      inputText.value,
      selectedAbstractType.value,
      selectedCategories.value,
      selectedKeywords.value,
      impact.value,
      synopsis.value
    );
    result.categories = selectedCategories.value;
    generatedAbstract.value = result;
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'An unknown error during abstract generation.';
  } finally {
    isLoading.value = false;
  }
};

const handleGenerateCreative = async () => {
  if (!inputText.value.trim()) {
    error.value = 'Please provide a core idea to expand.';
    return;
  }
  isLoading.value = true;
  loadingMessage.value = t('loading_messages.generating_creative');
  error.value = null;
  resetWorkflow();
  try {
    const result = await llm.generateCreativeAbstract(inputText.value);
    impact.value = result.impact;
    synopsis.value = result.synopsis;
    selectedKeywords.value = result.keywords;
    selectedAbstractType.value = 'Standard Abstract';
    generatedAbstract.value = result;
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'An unknown error during creative generation.';
  } finally {
    isLoading.value = false;
  }
};

const handleGenerateNanobana = () => {
  alert(
    'Nanobana Pro 3 enhanced generation is coming soon. This will require a premium API with payment gating.'
  );
};

const handleGenerateImage = async () => {
  let context = '';
  if (imageMode.value === 'creative') {
    if (!generatedAbstract.value) {
      error.value =
        'Please generate an abstract first to provide context for creative image generation.';
      return;
    }
    context = `Impact: ${generatedAbstract.value.impact}\nSynopsis: ${generatedAbstract.value.synopsis}`;
  } else if (!imageState.value.file) {
    error.value = 'Please upload an image for standard mode editing.';
    return;
  }

  isLoading.value = true;
  loadingMessage.value = t('loading_messages.generating_figure');
  error.value = null;
  generatedImage.value = null;
  try {
    const result = await llm.generateImage(imageState.value, context);
    generatedImage.value = `data:image/png;base64,${result}`;
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'An unknown error during image generation.';
  } finally {
    isLoading.value = false;
  }
};

const handleSaveAbstract = async () => {
  if (!generatedAbstract.value) return;

  try {
    const title = prompt('Enter a title for this abstract:');
    if (!title) return;

    await databaseService.saveAbstract({
      title,
      conference: 'ISMRM',
      abstractType: selectedAbstractType.value || 'Standard Abstract',
      abstractData: generatedAbstract.value,
      originalText: inputText.value,
      categories: selectedCategories.value,
      keywords: selectedKeywords.value,
      generationParameters: {
        provider: settings.value.provider,
        model: settings.value.model || 'gemini-2.5-pro',
        categories: selectedCategories.value,
        keywords: selectedKeywords.value,
        abstractType: selectedAbstractType.value || undefined,
      },
    });

    alert('Abstract saved successfully!');
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to save abstract';
  }
};

const handleClear = () => {
  if (confirm('Are you sure you want to clear all data? This will reset the workflow.')) {
    inputText.value = '';
    resetWorkflow();
    generatedImage.value = null;
    imageState.value = { file: null, specs: '', base64: null };
    error.value = null;
  }
};

const handleDeepUpdate = async () => {
  if (!generatedAbstract.value || !selectedAbstractType.value) return;

  isLoading.value = true;
  loadingMessage.value = t('loading_messages.deep_diving');
  error.value = null;

  try {
    // Use the current abstract as context for refinement
    const refinementPrompt = `Please refine and improve this abstract while maintaining its core message and structure. Focus on:
1. Clarity and precision of language
2. Stronger impact and significance statements
3. Better flow and coherence
4. More specific technical details where appropriate

Current Abstract:
${generatedAbstract.value.abstract}

Impact: ${generatedAbstract.value.impact}
Synopsis: ${generatedAbstract.value.synopsis}
Keywords: ${generatedAbstract.value.keywords.join(', ')}`;

    const result = await llm.generateFinalAbstract(
      refinementPrompt,
      selectedAbstractType.value,
      selectedCategories.value,
      selectedKeywords.value,
      impact.value,
      synopsis.value
    );

    result.categories = selectedCategories.value;
    generatedAbstract.value = result;
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to perform deep update';
  } finally {
    isLoading.value = false;
  }
};

// Load abstract from Abstract Manager
watch(abstractToLoad, (newAbstract) => {
  if (newAbstract) {
    inputText.value = newAbstract.originalText;
    generatedAbstract.value = newAbstract.abstractData;
    selectedCategories.value = newAbstract.categories || [];
    selectedKeywords.value = newAbstract.keywords;
    selectedAbstractType.value = newAbstract.abstractType;
    impact.value = newAbstract.abstractData.impact;
    synopsis.value = newAbstract.abstractData.synopsis;
    clearLoadedAbstract();
  }
});

// Setters for mode selectors
const setActiveTab = (tab: 'abstract' | 'figure') => {
  activeTab.value = tab;
};

const setAbstractMode = (mode: GenerationMode) => {
  abstractMode.value = mode;
};

const setImageMode = (mode: GenerationMode) => {
  imageMode.value = mode;
};
</script>
